/**
 * Mock/fallback station data used when the Radio Browser API returns empty results.
 *
 * Sources:
 *  BR → https://tudoradio.com/
 *  DE → https://www.deutschland.fm/ · https://onlineradiobox.com/de/
 *  US → https://onlineradiobox.com/us/
 *  GB → https://www.radio-uk.co.uk/radio/england
 *  FR → https://streema.com/radios/country/France
 *  ES → https://e-spanyol.com/spanish-online-radios.php → Spain
 *  MX → https://e-spanyol.com/spanish-online-radios.php → Mexico
 *  AR → https://e-spanyol.com/spanish-online-radios.php → Argentina
 *  JP → https://onlineradiobox.com/jp/?lang=en
 *  AU → https://www.radio-australia.org/
 */

import type { Station } from './radio-browser'

function mockStation(
  id: string,
  name: string,
  url: string,
  countrycode: string,
  country: string,
  tags: string,
  language: string,
  languagecodes: string,
  state = '',
  homepage = '',
  favicon = '',
  bitrate = 128,
  votes = 1000,
): Station {
  return {
    stationuuid: `mock-${id}`,
    name,
    url,
    url_resolved: url,
    homepage,
    favicon,
    tags,
    country,
    countrycode,
    state,
    language,
    languagecodes,
    votes,
    codec: 'MP3',
    bitrate,
    clickcount: votes * 2,
    clicktrend: 10,
    lastcheckoktime: '2025-01-01 00:00:00',
    hls: 0,
  }
}

// ─── Brazil ───────────────────────────────────────────────────────────────────
// Source: https://tudoradio.com/

const BR: Station[] = [
  mockStation(
    'br-jovem-pan-fm',
    'Jovem Pan FM',
    'https://jovempanfm.leanstream.co/JPFM-MP3',
    'BR', 'Brazil',
    'pop,rock,talk,news',
    'portuguese', 'pt', 'São Paulo',
    'https://jovempan.com.br',
    'https://jovempan.com.br/wp-content/themes/jovem-pan/assets/img/favicon.ico',
    128, 9500,
  ),
  mockStation(
    'br-antena-1',
    'Antena 1',
    'https://antenaone.leanstream.co/AAONE-MP3',
    'BR', 'Brazil',
    'mpb,pop,classic',
    'portuguese', 'pt', 'São Paulo',
    'https://antena1.com.br',
    'https://antena1.com.br/favicon.ico',
    128, 8200,
  ),
  mockStation(
    'br-cbn',
    'CBN',
    'https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_SPAAC',
    'BR', 'Brazil',
    'news,talk,journalism',
    'portuguese', 'pt', 'São Paulo',
    'https://cbn.com.br',
    'https://cbn.com.br/favicon.ico',
    128, 7800,
  ),
  mockStation(
    'br-radio-cultura-fm',
    'Rádio Cultura FM',
    'https://ice.fabricahost.com.br/culturabrasiliana',
    'BR', 'Brazil',
    'culture,mpb,classical',
    'portuguese', 'pt', 'São Paulo',
    'https://cultura.fm',
    '',
    128, 7000,
  ),
  mockStation(
    'br-mix-fm-sp',
    'Mix FM São Paulo',
    'https://mixfm.leanstream.co/MIXFM-MP3',
    'BR', 'Brazil',
    'pop,dance,electronic',
    'portuguese', 'pt', 'São Paulo',
    'https://mixfm.com.br',
    'https://mixfm.com.br/favicon.ico',
    128, 6500,
  ),
  mockStation(
    'br-radio-globo',
    'Rádio Globo',
    'https://globoradio.leanstream.co/RDGLO-MP3',
    'BR', 'Brazil',
    'talk,sport,news',
    'portuguese', 'pt', 'Rio de Janeiro',
    'https://radioglobo.com.br',
    '',
    128, 6200,
  ),
  mockStation(
    'br-radio-nacional',
    'Rádio Nacional AM 980',
    'https://radios.ebc.com.br/nacional',
    'BR', 'Brazil',
    'news,government,culture',
    'portuguese', 'pt', 'Brasília',
    'https://radionacional.ebc.com.br',
    '',
    64, 5800,
  ),
  mockStation(
    'br-itatiaia',
    'Rádio Itatiaia',
    'https://stream.itatiaia.com.br/mp3',
    'BR', 'Brazil',
    'news,sport,talk',
    'portuguese', 'pt', 'Minas Gerais',
    'https://itatiaia.com.br',
    'https://itatiaia.com.br/favicon.ico',
    128, 5500,
  ),
  mockStation(
    'br-radio-band-fm',
    'Band FM São Paulo',
    'https://bandfm.leanstream.co/BNDSP-MP3',
    'BR', 'Brazil',
    'pop,rock,entertainment',
    'portuguese', 'pt', 'São Paulo',
    'https://band.com.br/bandfm',
    '',
    128, 5200,
  ),
  mockStation(
    'br-radio-transamazonica',
    'Rádio Transamazônica',
    'https://server1.servidorderadio.com.br:8006/stream',
    'BR', 'Brazil',
    'regional,folk,forró',
    'portuguese', 'pt', 'Pará',
    '',
    '',
    64, 2000,
  ),
  mockStation(
    'br-radio-verdade',
    'Rádio Verdade FM',
    'https://ssl.rokedahost.com.br:9136/stream',
    'BR', 'Brazil',
    'gospel,christian',
    'portuguese', 'pt', 'Rio de Janeiro',
    '',
    '',
    64, 1800,
  ),
  mockStation(
    'br-radio-uol',
    'UOL FM 95.7',
    'https://playerservices.streamtheworld.com/api/livestream-redirect/UOLFM_AAC',
    'BR', 'Brazil',
    'pop,electronic,dance',
    'portuguese', 'pt', 'São Paulo',
    'https://uol.com.br',
    '',
    128, 4400,
  ),
]

// ─── United States ────────────────────────────────────────────────────────────
// Source: https://onlineradiobox.com/us/

const US: Station[] = [
  mockStation(
    'us-npr',
    'NPR Radio',
    'https://npr-ice.streamguys1.com/live.mp3',
    'US', 'The United States Of America',
    'news,public,talk,culture',
    'english', 'en', 'Washington D.C.',
    'https://npr.org',
    'https://npr.org/favicon.ico',
    128, 15000,
  ),
  mockStation(
    'us-977-todays-hits',
    '.977 Today\'s Hits',
    'https://playerservices.streamtheworld.com/api/livestream-redirect/977MHZ.mp3',
    'US', 'The United States Of America',
    'pop,top 40,hits',
    'english', 'en', '',
    'https://977music.com',
    '',
    128, 13000,
  ),
  mockStation(
    'us-101-smooth-jazz',
    '101 Smooth Jazz',
    'https://playerservices.streamtheworld.com/api/livestream-redirect/SMOOTHJAZZ.mp3',
    'US', 'The United States Of America',
    'jazz,smooth jazz,easy listening,instrumental',
    'english', 'en', '',
    'https://101smoothjazz.com',
    '',
    128, 11500,
  ),
  mockStation(
    'us-kexp',
    'KEXP 90.3 FM',
    'https://kexp-mp3-128.streamguys1.com/kexp128.mp3',
    'US', 'The United States Of America',
    'indie,alternative,rock',
    'english', 'en', 'Seattle',
    'https://kexp.org',
    'https://kexp.org/favicon.ico',
    128, 11000,
  ),
  mockStation(
    'us-chilltrax',
    'Chilltrax',
    'https://playerservices.streamtheworld.com/api/livestream-redirect/CHILLTRAX.mp3',
    'US', 'The United States Of America',
    'electronic,downtempo,chill-out,ambient',
    'english', 'en', '',
    'https://chilltrax.com',
    '',
    128, 10000,
  ),
  mockStation(
    'us-soma-groove-salad',
    'SomaFM Groove Salad',
    'https://ice6.somafm.com/groovesalad-128-mp3',
    'US', 'The United States Of America',
    'ambient,chill,electronic',
    'english', 'en', 'San Francisco',
    'https://somafm.com',
    '',
    128, 9500,
  ),
  mockStation(
    'us-181fm-buzz',
    '181.FM The Buzz',
    'https://listen.181fm.com/181-buzz_128k.mp3',
    'US', 'The United States Of America',
    'alternative rock,indie,grunge',
    'english', 'en', '',
    'https://181.fm',
    '',
    128, 8500,
  ),
  mockStation(
    'us-classic-rock-florida',
    'Classic Rock Florida',
    'https://rfcmedia2.streamguys1.com/ClassicRockFlorida.mp3',
    'US', 'The United States Of America',
    'classic rock,rock,80s,70s,60s',
    'english', 'en', 'Florida',
    '',
    '',
    128, 8000,
  ),
  mockStation(
    'us-fox-news-talk',
    'FOX News Talk',
    'https://live.amperwave.net/direct/foxnewsradio-foxnewsmp3-imc',
    'US', 'The United States Of America',
    'news,talk',
    'english', 'en', 'New York',
    'https://radio.foxnews.com',
    '',
    128, 7500,
  ),
  mockStation(
    'us-smooth-jazz-247',
    'Smooth Jazz 247',
    'https://playerservices.streamtheworld.com/api/livestream-redirect/SMOOTHJAZZ247.mp3',
    'US', 'The United States Of America',
    'jazz,smooth jazz,soul,r&b',
    'english', 'en', '',
    '',
    '',
    128, 6500,
  ),
]

// ─── United Kingdom ───────────────────────────────────────────────────────────
// Source: https://www.radio-uk.co.uk/radio/england

const GB: Station[] = [
  mockStation(
    'gb-talksport',
    'talkSPORT',
    'https://radio.talksport.com/stream',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    'sport,talk,football',
    'english', 'en', 'London',
    'https://talksport.com',
    '',
    128, 20000,
  ),
  mockStation(
    'gb-capital-london',
    'Capital London',
    'https://media-ice.musicradio.com/CapitalMP3',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    'pop,top 40,hits,contemporary',
    'english', 'en', 'London',
    'https://capitalfm.com',
    '',
    128, 19000,
  ),
  mockStation(
    'gb-bbc-radio-1',
    'BBC Radio 1',
    'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    'pop,charts,dance,youth',
    'english', 'en', 'London',
    'https://bbc.co.uk/radio1',
    '',
    128, 18000,
  ),
  mockStation(
    'gb-bbc-radio-2',
    'BBC Radio 2',
    'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_two',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    'pop,rock,easy listening,mixed',
    'english', 'en', 'London',
    'https://bbc.co.uk/radio2',
    '',
    128, 17500,
  ),
  mockStation(
    'gb-bbc-radio-4',
    'BBC Radio 4',
    'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    'talk,news,culture,drama',
    'english', 'en', 'London',
    'https://bbc.co.uk/radio4',
    '',
    128, 16000,
  ),
  mockStation(
    'gb-smooth-radio',
    'Smooth Radio',
    'https://media-ice.musicradio.com/SmoothMP3',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    'easy listening,smooth,pop',
    'english', 'en', 'London',
    'https://smoothradio.com',
    '',
    128, 15000,
  ),
  mockStation(
    'gb-heart-uk',
    'Heart UK',
    'https://media-ice.musicradio.com/HeartMP3',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    'pop,hits',
    'english', 'en', 'England',
    'https://heart.co.uk',
    '',
    128, 14000,
  ),
  mockStation(
    'gb-bbc-world-service',
    'BBC World Service',
    'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    'news,world,talk,international',
    'english', 'en', 'London',
    'https://bbc.co.uk/worldservice',
    '',
    128, 13000,
  ),
  mockStation(
    'gb-radio-x',
    'Radio X',
    'https://media-ice.musicradio.com/RadioXMP3',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    'rock,indie,alternative',
    'english', 'en', 'London',
    'https://radiox.co.uk',
    '',
    128, 12000,
  ),
  mockStation(
    'gb-heart-80s',
    'Heart 80s',
    'https://media-ice.musicradio.com/Heart80sMP3',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    '80s,pop,oldies,hits',
    'english', 'en', 'England',
    'https://heart.co.uk/80s',
    '',
    128, 11000,
  ),
  mockStation(
    'gb-virgin-radio',
    'Virgin Radio UK',
    'https://stream.thisisdax.com/VirginRadioUK.mp3',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    'rock,pop,hits',
    'english', 'en', 'London',
    'https://virginradio.co.uk',
    '',
    128, 10000,
  ),
  mockStation(
    'gb-times-radio',
    'Times Radio',
    'https://timesradio.wireless.radio/stream',
    'GB', 'The United Kingdom Of Great Britain And Northern Ireland',
    'news,talk',
    'english', 'en', 'London',
    'https://thetimes.co.uk/radio',
    '',
    128, 9000,
  ),
]

// ─── Germany ──────────────────────────────────────────────────────────────────
// Source: https://www.deutschland.fm/ · https://onlineradiobox.com/de/

const DE: Station[] = [
  mockStation(
    'de-antenne-bayern',
    'Antenne Bayern',
    'https://stream.antenne.de/antenne',
    'DE', 'Germany',
    'pop,rock,hits,talk',
    'german', 'de', 'Bayern',
    'https://antenne.de',
    '',
    128, 18000,
  ),
  mockStation(
    'de-1live',
    '1LIVE',
    'https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3',
    'DE', 'Germany',
    'pop,youth,contemporary',
    'german', 'de', 'Nordrhein-Westfalen',
    'https://1live.de',
    '',
    128, 16000,
  ),
  mockStation(
    'de-deutschlandfunk',
    'Deutschlandfunk',
    'https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3',
    'DE', 'Germany',
    'news,talk,culture',
    'german', 'de', '',
    'https://deutschlandfunk.de',
    '',
    128, 14000,
  ),
  mockStation(
    'de-swr3',
    'SWR3',
    'https://liveradio.swr.de/sw331ch/swr3/',
    'DE', 'Germany',
    'pop,hits,youth,entertainment',
    'german', 'de', 'Baden-Württemberg',
    'https://swr3.de',
    '',
    128, 13500,
  ),
  mockStation(
    'de-ndr2',
    'NDR 2',
    'https://dispatcher.rndfnk.com/ndr/ndr2/live/mp3/high',
    'DE', 'Germany',
    'pop,entertainment,hits',
    'german', 'de', 'Hamburg',
    'https://ndr.de/ndr2',
    '',
    128, 13000,
  ),
  mockStation(
    'de-bayern3',
    'Bayern 3',
    'https://dispatcher.rndfnk.com/br/br3/live/mp3/high',
    'DE', 'Germany',
    'pop,hits,lifestyle,bavarian',
    'german', 'de', 'Bayern',
    'https://br.de/bayern3',
    '',
    128, 12500,
  ),
  mockStation(
    'de-rock-antenne',
    'Rock Antenne',
    'https://stream.rockantenne.de/rockantenne/stream/mp3',
    'DE', 'Germany',
    'rock,classic rock,hard rock',
    'german', 'de', 'Bayern',
    'https://rockantenne.de',
    '',
    128, 12000,
  ),
  mockStation(
    'de-80s80s',
    '80s80s',
    'https://streams.80s80s.de/80s80s/mp3-192/',
    'DE', 'Germany',
    '80s,pop,oldies,retro',
    'german', 'de', '',
    'https://80s80s.de',
    '',
    192, 11500,
  ),
  mockStation(
    'de-klassik-radio',
    'Klassik Radio',
    'https://stream.klassikradio.de/live/mp3-128/stream.klassikradio.de/',
    'DE', 'Germany',
    'classical,lounge,soundtrack,instrumental',
    'german', 'de', '',
    'https://klassikradio.de',
    '',
    128, 11000,
  ),
  mockStation(
    'de-radio-eins',
    'radioeins',
    'https://dispatcher.rndfnk.com/rbb/radioeins/live/mp3/high',
    'DE', 'Germany',
    'pop,indie,culture,alternative',
    'german', 'de', 'Berlin',
    'https://radioeins.de',
    '',
    128, 10000,
  ),
  mockStation(
    'de-mdr-sputnik',
    'MDR SPUTNIK',
    'https://mdr-sputnik-live.icecastssl.mdr.de/mdr/sputnik/live/mp3/128/stream.mp3',
    'DE', 'Germany',
    'youth,pop,electronic,alternative',
    'german', 'de', 'Sachsen',
    'https://sputnik.de',
    '',
    128, 9500,
  ),
  mockStation(
    'de-sunshine-live',
    'Radio Sunshine Live',
    'https://stream.sunshine-live.de/live/mp3-128/stream.sunshine-live.de/',
    'DE', 'Germany',
    'dance,techno,electronic',
    'german', 'de', 'Mannheim',
    'https://sunshine-live.de',
    '',
    128, 9000,
  ),
  mockStation(
    'de-you-fm',
    'YOU FM',
    'https://dispatcher.rndfnk.com/hr/youfm/live/mp3/high',
    'DE', 'Germany',
    'youth,pop,hip-hop,alternative',
    'german', 'de', 'Hessen',
    'https://youfm.de',
    '',
    128, 8500,
  ),
  mockStation(
    'de-radio-paloma',
    'Radio Paloma',
    'https://stream.radiopaloma.de/radiopaloma/mp3-128/radiopaloma.mp3',
    'DE', 'Germany',
    'schlager,folk,pop,german',
    'german', 'de', '',
    'https://radiopaloma.de',
    '',
    128, 8000,
  ),
  mockStation(
    'de-wdr2',
    'WDR 2',
    'https://wdr-wdr2-live.icecastssl.wdr.de/wdr/wdr2/live/mp3/128/stream.mp3',
    'DE', 'Germany',
    'pop,news,entertainment',
    'german', 'de', 'Nordrhein-Westfalen',
    'https://wdr.de/wdr2',
    '',
    128, 7500,
  ),
]

// ─── France ───────────────────────────────────────────────────────────────────
// Source: https://streema.com/radios/country/France

const FR: Station[] = [
  mockStation(
    'fr-rtl',
    'RTL',
    'https://streaming.radio.rtl.fr/rtl-1-44-128',
    'FR', 'France',
    'news,entertainment,talk',
    'french', 'fr', 'Paris',
    'https://rtl.fr',
    '',
    128, 15000,
  ),
  mockStation(
    'fr-europe-1',
    'Europe 1',
    'https://europe1.leanstream.co/EUROPE1-MP3',
    'FR', 'France',
    'news,sport,current affairs,talk',
    'french', 'fr', 'Paris',
    'https://europe1.fr',
    '',
    128, 13500,
  ),
  mockStation(
    'fr-france-inter',
    'France Inter',
    'https://icecast.radiofrance.fr/franceinter-midfi.mp3',
    'FR', 'France',
    'talk,news,culture',
    'french', 'fr', 'Paris',
    'https://franceinter.fr',
    '',
    128, 13000,
  ),
  mockStation(
    'fr-radio-france-info',
    'France Info',
    'https://icecast.radiofrance.fr/franceinfo-midfi.mp3',
    'FR', 'France',
    'news,information,talk',
    'french', 'fr', 'Paris',
    'https://francetvinfo.fr/radio',
    '',
    128, 12500,
  ),
  mockStation(
    'fr-nrj',
    'NRJ',
    'https://cdn.nrjaudio.fm/audio1/fr/30001/mp3_128.mp3',
    'FR', 'France',
    'pop,dance,hits,top 40',
    'french', 'fr', 'Paris',
    'https://nrj.fr',
    '',
    128, 12000,
  ),
  mockStation(
    'fr-radio-classique',
    'Radio Classique',
    'https://radioclassique.leanstream.co/RADCLA-MP3',
    'FR', 'France',
    'classical,opera,information',
    'french', 'fr', 'Paris',
    'https://radioclassique.fr',
    '',
    128, 11000,
  ),
  mockStation(
    'fr-tsf-jazz',
    'TSF Jazz',
    'https://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3',
    'FR', 'France',
    'jazz,variety',
    'french', 'fr', 'Paris',
    'https://tsfjazz.com',
    '',
    128, 10000,
  ),
  mockStation(
    'fr-cherie-fm',
    'Chérie FM',
    'https://cheriefm.leanstream.co/CHEFM-MP3',
    'FR', 'France',
    'pop,love songs,romantic,french pop',
    'french', 'fr', 'Paris',
    'https://cheriefm.fr',
    '',
    128, 9500,
  ),
  mockStation(
    'fr-rfi',
    'RFI - Radio France Internationale',
    'https://rfifr.leanstream.co/RFIFR-MP3',
    'FR', 'France',
    'news,world,international,talk',
    'french', 'fr', 'Paris',
    'https://rfi.fr',
    '',
    128, 9000,
  ),
  mockStation(
    'fr-jazz-radio',
    'Jazz Radio',
    'https://jazzradio.ice.infomaniak.ch/jazzradio-high.mp3',
    'FR', 'France',
    'jazz,soul,blues',
    'french', 'fr', 'Lyon',
    'https://jazzradio.fr',
    '',
    128, 8000,
  ),
]

// ─── Spain ────────────────────────────────────────────────────────────────────
// Source: https://e-spanyol.com/spanish-online-radios.php → Spain

const ES: Station[] = [
  mockStation(
    'es-cadena-ser',
    'Cadena SER',
    'https://19093.live.streamtheworld.com/CADENASERAAC.aac',
    'ES', 'Spain',
    'news,talk,sport',
    'spanish', 'es', 'Madrid',
    'https://cadenaser.com',
    '',
    128, 12000,
  ),
  mockStation(
    'es-los-40',
    'Los 40',
    'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_SC',
    'ES', 'Spain',
    'pop,hits,charts',
    'spanish', 'es', 'Madrid',
    'https://los40.com',
    '',
    128, 10000,
  ),
  mockStation(
    'es-cadena-dial',
    'Cadena Dial',
    'https://20073.live.streamtheworld.com/CADENADIALAAC.aac',
    'ES', 'Spain',
    'pop,latin,hits',
    'spanish', 'es', 'Madrid',
    'https://cadenadial.com',
    '',
    128, 9500,
  ),
  mockStation(
    'es-cope',
    'COPE',
    'https://net1-cope-flucast.flumotion.com/cope/net1.mp3',
    'ES', 'Spain',
    'news,talk,sport,religion',
    'spanish', 'es', 'Madrid',
    'https://cope.es',
    '',
    128, 9000,
  ),
  mockStation(
    'es-kiss-fm',
    'Kiss FM',
    'https://kissfm.kissfmradio.cires21.com/kissfm.mp3',
    'ES', 'Spain',
    'pop,dance,hits,electronic',
    'spanish', 'es', 'Madrid',
    'https://kissfm.es',
    '',
    128, 8500,
  ),
  mockStation(
    'es-radio-marca',
    'Radio Marca',
    'https://radiomarca.streaming-pro.com:8031/radiomarca.mp3',
    'ES', 'Spain',
    'sport,football,talk',
    'spanish', 'es', 'Madrid',
    'https://radiomarca.com',
    '',
    128, 7500,
  ),
  mockStation(
    'es-onda-madrid',
    'Onda Madrid',
    'https://telemadridhls-live.hls.adaptive.level3.net/telemadrid/tvradio/bitrate_1.m3u8',
    'ES', 'Spain',
    'news,talk,regional',
    'spanish', 'es', 'Madrid',
    'https://telemadrid.es',
    '',
    128, 6500,
  ),
  mockStation(
    'es-radio-universidad-salamanca',
    'Radio Universidad de Salamanca',
    'https://212.128.140.98:8000/usalradio.mp3',
    'ES', 'Spain',
    'culture,education,talk',
    'spanish', 'es', 'Salamanca',
    '',
    '',
    128, 3000,
  ),
]

// ─── Mexico ───────────────────────────────────────────────────────────────────
// Source: https://e-spanyol.com/spanish-online-radios.php → Mexico

const MX: Station[] = [
  mockStation(
    'mx-radio-unam-fm',
    'Radio UNAM FM',
    'http://server1.usatelk.com:27547/',
    'MX', 'Mexico',
    'culture,classical,education,jazz',
    'spanish', 'es', 'Mexico City',
    'https://radio.unam.mx',
    '',
    128, 9000,
  ),
  mockStation(
    'mx-alfa-913',
    'Alfa 91.3 FM',
    'http://18553.live.streamtheworld.com/XHFAJ_FMAAC.aac',
    'MX', 'Mexico',
    'pop,hits,contemporary',
    'spanish', 'es', 'Mexico City',
    'https://alfa913.com',
    '',
    128, 8500,
  ),
  mockStation(
    'mx-radio-centro-977',
    'Radio Centro 97.7 FM',
    'http://19803.live.streamtheworld.com/XERC_FMAAC.aac',
    'MX', 'Mexico',
    'pop,music,entertainment',
    'spanish', 'es', 'Mexico City',
    'https://radiocentro.com.mx',
    '',
    128, 8000,
  ),
  mockStation(
    'mx-planeta-947',
    'Planeta Radio 94.7',
    'http://15053.live.streamtheworld.com/XHDK_FMAAC.aac',
    'MX', 'Mexico',
    'rock,alternative,pop',
    'spanish', 'es', 'Guadalajara',
    '',
    '',
    128, 7500,
  ),
  mockStation(
    'mx-ibero-900',
    'Ibero 90.0',
    'http://noasrv.caster.fm:10182/live',
    'MX', 'Mexico',
    'indie,alternative,culture',
    'spanish', 'es', 'Mexico City',
    'https://ibero909.fm',
    '',
    128, 7000,
  ),
  mockStation(
    'mx-radio-anahuac',
    'Radio Anáhuac',
    'https://stream.anahuac.mx/radioanahuac/live.mp4/playlist.m3u8',
    'MX', 'Mexico',
    'culture,education,talk',
    'spanish', 'es', 'Mexico City',
    'https://anahuac.mx',
    '',
    128, 6000,
  ),
  mockStation(
    'mx-joya-937',
    'Joya 93.7 FM',
    'http://18493.live.streamtheworld.com/XEJP_FMAAC.aac',
    'MX', 'Mexico',
    'pop,oldies,easy listening',
    'spanish', 'es', 'Mexico City',
    '',
    '',
    128, 5500,
  ),
  mockStation(
    'mx-uam-radio-941',
    'UAM Radio 94.1 FM',
    'http://streamingv2.shoutcast.com/uam-radio-941',
    'MX', 'Mexico',
    'culture,education,talk,news',
    'spanish', 'es', 'Mexico City',
    '',
    '',
    128, 5000,
  ),
]

// ─── Argentina ────────────────────────────────────────────────────────────────
// Source: https://e-spanyol.com/spanish-online-radios.php → Argentina

const AR: Station[] = [
  mockStation(
    'ar-radio-10',
    'Radio 10 AM 710',
    'https://s6.stweb.tv/radio10/live/chunks.m3u8',
    'AR', 'Argentina',
    'news,talk,sport',
    'spanish', 'es', 'Buenos Aires',
    'https://radio10.com.ar',
    '',
    128, 12000,
  ),
  mockStation(
    'ar-continental',
    'Continental AM 590',
    'http://20823.live.streamtheworld.com/CONTINENTALAAC.aac',
    'AR', 'Argentina',
    'news,talk,sport',
    'spanish', 'es', 'Buenos Aires',
    'https://continental.com.ar',
    '',
    128, 11000,
  ),
  mockStation(
    'ar-cadena3',
    'Cadena 3',
    'https://playerservices.streamtheworld.com/api/livestream-redirect/CADENA3.mp3',
    'AR', 'Argentina',
    'news,talk,entertainment',
    'spanish', 'es', 'Córdoba',
    'https://cadena3.com',
    '',
    128, 10000,
  ),
  mockStation(
    'ar-los-40',
    'Los 40 Principales',
    'https://18303.live.streamtheworld.com/LOS40_ARGENTINAAAC.aac',
    'AR', 'Argentina',
    'pop,hits,charts',
    'spanish', 'es', 'Buenos Aires',
    '',
    '',
    128, 9000,
  ),
  mockStation(
    'ar-rock-pop',
    'Rock & Pop 95.9 FM',
    'http://play-rockandpop.cdn.sion.com:1935/rockandpop/audioweb/chunklist_w1085215581.m3u8',
    'AR', 'Argentina',
    'rock,pop,alternative',
    'spanish', 'es', 'Buenos Aires',
    'https://rockandpop.com.ar',
    '',
    128, 8500,
  ),
  mockStation(
    'ar-metro-951',
    'Metro 95.1',
    'https://metro-on-demand.edge-apps.net/api/1.0/playlist/live',
    'AR', 'Argentina',
    'pop,dance,urban',
    'spanish', 'es', 'Buenos Aires',
    'https://metro951.com',
    '',
    128, 8000,
  ),
  mockStation(
    'ar-radio-aspen',
    'Radio Aspen 102.3',
    'http://18743.live.streamtheworld.com/ASPENAAC.aac',
    'AR', 'Argentina',
    'easy listening,pop,adult contemporary',
    'spanish', 'es', 'Buenos Aires',
    '',
    '',
    128, 7000,
  ),
  mockStation(
    'ar-radio-nacional',
    'Radio Nacional AM 870',
    'http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad1',
    'AR', 'Argentina',
    'news,culture,government',
    'spanish', 'es', 'Buenos Aires',
    'https://radionacional.com.ar',
    '',
    128, 6500,
  ),
]

// ─── Japan ────────────────────────────────────────────────────────────────────
// Source: https://onlineradiobox.com/jp/?lang=en

const JP: Station[] = [
  mockStation(
    'jp-nhk-world',
    'NHK World Radio Japan',
    'https://nhkworld.hls.nhk.or.jp/live/english/hd/playlist.m3u8',
    'JP', 'Japan',
    'news,culture,talk,international',
    'japanese', 'ja', 'Tokyo',
    'https://nhk.or.jp/nhkworld',
    '',
    128, 10000,
  ),
  mockStation(
    'jp-nhk-radio1',
    'NHK Radio 1',
    'https://nhkradioakr1-i.akamaihd.net/hls/live/511929/1-r1/1-r1-01.m3u8',
    'JP', 'Japan',
    'talk,education,news',
    'japanese', 'ja', 'Tokyo',
    'https://nhk.or.jp',
    '',
    128, 9000,
  ),
  mockStation(
    'jp-nhk-fm',
    'NHK Radio FM',
    'https://nhkradioakrfm-i.akamaihd.net/hls/live/511929/1-fm/1-fm-01.m3u8',
    'JP', 'Japan',
    'classical,culture,music',
    'japanese', 'ja', 'Tokyo',
    'https://nhk.or.jp',
    '',
    128, 8500,
  ),
  mockStation(
    'jp-j-wave',
    'J-WAVE 81.3 FM',
    'https://jwave.leanstream.co/JWAVEFM-MP3',
    'JP', 'Japan',
    'pop,jazz,urban',
    'japanese', 'ja', 'Tokyo',
    'https://j-wave.co.jp',
    '',
    128, 8000,
  ),
  mockStation(
    'jp-j1-hits',
    'J1 HITS',
    'http://streams.torontocast.stream:1610/stream',
    'JP', 'Japan',
    'j-pop,pop,hits,japanese',
    'japanese', 'ja', 'Tokyo',
    'https://j1fm.tokyo',
    '',
    128, 7000,
  ),
  mockStation(
    'jp-shonan-beach-fm',
    'Shonan Beach FM',
    'https://shonanbeachfm.leanstream.co/SBNFM-MP3',
    'JP', 'Japan',
    'jazz,adult contemporary,oldies,hits',
    'japanese', 'ja', 'Kanagawa',
    'https://shonanbeachfm.com',
    '',
    128, 6000,
  ),
  mockStation(
    'jp-musashino-fm',
    'Musashino FM',
    'https://musashino.fm/stream',
    'JP', 'Japan',
    'jazz,news,talk,community',
    'japanese', 'ja', 'Tokyo',
    'https://musashino.fm',
    '',
    128, 5000,
  ),
  mockStation(
    'jp-vocaloid-radio',
    'Vocaloid Radio',
    'https://vocaloidradio.com/stream',
    'JP', 'Japan',
    'j-pop,anime,vocaloid,electronic',
    'japanese', 'ja', '',
    'https://vocaloidradio.com',
    '',
    128, 4500,
  ),
]

// ─── Australia ────────────────────────────────────────────────────────────────
// Source: https://www.radio-australia.org/

const AU: Station[] = [
  mockStation(
    'au-triple-j',
    'triple j',
    'https://live-radio01.mediahubaustralia.com/2TJW/mp3/',
    'AU', 'Australia',
    'indie,alternative,rock,youth',
    'english', 'en', 'Sydney',
    'https://abc.net.au/triplej',
    '',
    128, 14000,
  ),
  mockStation(
    'au-2gb-sydney',
    '2GB Sydney',
    'https://19893.live.streamtheworld.com/2GB_SC',
    'AU', 'Australia',
    'talk,news',
    'english', 'en', 'Sydney',
    'https://2gb.com',
    '',
    128, 13000,
  ),
  mockStation(
    'au-3aw-melbourne',
    '3AW Melbourne',
    'https://19773.live.streamtheworld.com/3AW_SC',
    'AU', 'Australia',
    'talk,news',
    'english', 'en', 'Melbourne',
    'https://3aw.com.au',
    '',
    128, 12500,
  ),
  mockStation(
    'au-abc-news-radio',
    'ABC News Radio',
    'https://live-radio01.mediahubaustralia.com/NewsRadio/mp3/',
    'AU', 'Australia',
    'news,talk',
    'english', 'en', 'Sydney',
    'https://abc.net.au/newsradio',
    '',
    128, 12000,
  ),
  mockStation(
    'au-kiis-1065',
    'KIIS 106.5 FM',
    'https://18263.live.streamtheworld.com/KIISFM_SC',
    'AU', 'Australia',
    'pop,contemporary,hits',
    'english', 'en', 'Sydney',
    'https://kiis1065.com.au',
    '',
    128, 11500,
  ),
  mockStation(
    'au-smooth-fm-953',
    'Smooth FM 95.3',
    'https://18383.live.streamtheworld.com/SMOOTHFM_SC',
    'AU', 'Australia',
    'easy listening,adult contemporary,smooth',
    'english', 'en', 'Sydney',
    'https://smoothfm.com.au',
    '',
    128, 11000,
  ),
  mockStation(
    'au-nova-969',
    'Nova 96.9',
    'https://playerservices.streamtheworld.com/api/livestream-redirect/NOVAFM.mp3',
    'AU', 'Australia',
    'pop,contemporary,hits',
    'english', 'en', 'Sydney',
    'https://nova969.com.au',
    '',
    128, 10500,
  ),
  mockStation(
    'au-abc-radio-national',
    'ABC Radio National',
    'https://live-radio01.mediahubaustralia.com/2RNW/mp3/',
    'AU', 'Australia',
    'news,culture,talk',
    'english', 'en', 'Sydney',
    'https://abc.net.au/radionational',
    '',
    128, 10000,
  ),
  mockStation(
    'au-gold-1043',
    'Gold 104.3 FM',
    'https://18513.live.streamtheworld.com/GOLDFM_SC',
    'AU', 'Australia',
    'oldies,classic hits',
    'english', 'en', 'Melbourne',
    'https://gold1043.com.au',
    '',
    128, 9500,
  ),
  mockStation(
    'au-abc-classic-fm',
    'ABC Classic FM',
    'https://live-radio01.mediahubaustralia.com/FMW/mp3/',
    'AU', 'Australia',
    'classical,culture',
    'english', 'en', 'Sydney',
    'https://abc.net.au/classic',
    '',
    128, 9000,
  ),
  mockStation(
    'au-702-abc-sydney',
    '702 ABC Sydney',
    'https://live-radio01.mediahubaustralia.com/2BLW/mp3/',
    'AU', 'Australia',
    'news,talk,culture',
    'english', 'en', 'Sydney',
    'https://abc.net.au/sydney',
    '',
    128, 8500,
  ),
  mockStation(
    'au-triple-m',
    'Triple M',
    'https://18823.live.streamtheworld.com/TRIPLE_M_SC',
    'AU', 'Australia',
    'rock,pop,classic rock',
    'english', 'en', 'Sydney',
    'https://triplem.com.au',
    '',
    128, 8000,
  ),
]

// ─── Canada ───────────────────────────────────────────────────────────────────

const CA: Station[] = [
  mockStation(
    'ca-cbc-radio-one',
    'CBC Radio One',
    'https://cbcliveradio.cbc.ca/live/cbcr1ottawa.stream/playlist.m3u8',
    'CA', 'Canada',
    'news,talk,culture',
    'english', 'en', 'Ottawa',
    'https://cbc.ca/radio',
    '',
    128, 10000,
  ),
  mockStation(
    'ca-iheartradio-toronto',
    'iHeartRadio Toronto',
    'https://radio.iheart.com/stream/toronto',
    'CA', 'Canada',
    'pop,hits,mainstream',
    'english', 'en', 'Toronto',
    'https://iheart.com',
    '',
    128, 7000,
  ),
]

// ─── Portugal ─────────────────────────────────────────────────────────────────

const PT: Station[] = [
  mockStation(
    'pt-radio-comercial',
    'Rádio Comercial',
    'https://stream-relocator.play.totalplayip.com/stream-m/radiocomercial/mp3/icecast.audio',
    'PT', 'Portugal',
    'pop,hits,mainstream',
    'portuguese', 'pt', 'Lisbon',
    'https://radiocomercial.iol.pt',
    '',
    128, 9000,
  ),
  mockStation(
    'pt-antena-1',
    'Antena 1',
    'https://streaming-live.rtp.pt/liveradio/antena1/index.m3u8',
    'PT', 'Portugal',
    'news,culture,talk',
    'portuguese', 'pt', 'Lisbon',
    'https://rtp.pt/antena1',
    '',
    128, 8000,
  ),
]

// ─── Index ────────────────────────────────────────────────────────────────────

const MOCK_BY_COUNTRY: Record<string, Station[]> = {
  BR,
  US,
  GB,
  DE,
  FR,
  ES,
  MX,
  AR,
  JP,
  AU,
  CA,
  PT,
}

/**
 * Returns mock stations for a given ISO country code.
 * Falls back to an empty array if the country has no mock data.
 */
export function getMockStationsByCountry(countrycode: string): Station[] {
  return MOCK_BY_COUNTRY[countrycode.toUpperCase()] ?? []
}
