import { trackSelfDescribingEvent, type CommonEventProperties, type SelfDescribingJson } from '@snowplow/browser-tracker';
// Automatically generated by Snowtype

/**
 * Fired when a user starts listening to a podcast episode
 */
export type PodcastEpisodeStarted = {
    /**
     * The unique identifier of the podcast episode
     */
    episode_id: string;
    /**
     * The display name of the podcast episode
     */
    episode_name: string;
    /**
     * Name of the guest featured in this episode, if any
     */
    guest_name?: null | string;
}

/**
 * Fired when a user unsubscribes from a podcast
 */
export type PodcastUnsubscribed = {
    /**
     * The unique identifier of the podcast
     */
    podcast_id: string;
    /**
     * The display name of the podcast
     */
    podcast_name: string;
}

/**
 * Fired when a user starts playing a playlist
 */
export type PlaylistStarted = {
    /**
     * The unique identifier of the playlist
     */
    playlist_id: string;
    /**
     * The display name of the playlist
     */
    playlist_name: string;
}

/**
 * Fired when a user visits a podcast detail page
 */
export type PodcastVisited = {
    /**
     * The unique identifier of the podcast
     */
    podcast_id: string;
    /**
     * The display name of the podcast
     */
    podcast_name: string;
}

/**
 * Fired when a user visits a radio station detail page
 */
export type RadioVisited = {
    /**
     * City where the station is based (not always available from the API)
     */
    city?: null | string;
    /**
     * List of genres/tags associated with the station
     */
    genres?: string[];
    /**
     * State or region where the station is based
     */
    state?: null | string;
    /**
     * The unique UUID of the radio station
     */
    station_id: string;
    /**
     * The display name of the radio station
     */
    station_name: string;
}

/**
 * Fired when a user visits a genre page
 */
export type GenreVisited = {
    /**
     * The name of the genre the user visited
     */
    genre_name: string;
}

/**
 * Fired when a user visits a country page
 */
export type CountryVisited = {
    /**
     * The full display name of the country (e.g. "Brazil")
     */
    country_name: string;
    /**
     * The ISO 3166-1 alpha-2 country code (e.g. "BR")
     */
    country_code: string;
}

/**
 * Fired when a user subscribes to a podcast
 */
export type PodcastSubscribed = {
    /**
     * The unique identifier of the podcast
     */
    podcast_id: string;
    /**
     * The display name of the podcast
     */
    podcast_name: string;
}

/**
 * Creates a Snowplow Event Specification entity.
 */
export function createEventSpecification(eventSpecification: Omit<EventSpecification, 'data_product_domain'> & Partial<Pick<EventSpecification, 'data_product_domain'>>){
    return {
        schema:
            'iglu:com.snowplowanalytics.snowplow/event_specification/jsonschema/1-0-4',
        data: eventSpecification,
    }
}

/**
 * Automatically attached context for event specifications
 */
interface EventSpecification {
    id: string;
    version: number;
    name: string;
    data_product_id: string;
    data_product_name: string;
    data_product_domain?: string;
}

type ContextsOrTimestamp<T = any> = Omit<CommonEventProperties<T>, 'context'> & { context?: SelfDescribingJson<T>[] | null | undefined }
/**
 * Track a Snowplow event for PodcastEpisodeStarted.
 * Fired when a user starts listening to a podcast episode
 */
export function trackPodcastEpisodeStarted<T extends {} = any>(podcastEpisodeStarted: PodcastEpisodeStarted & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = podcastEpisodeStarted;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosradioexplorer/podcast_episode_started/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow PodcastEpisodeStarted entity.
 */
export function createPodcastEpisodeStarted(podcastEpisodeStarted: PodcastEpisodeStarted){
    return {
        schema: 'iglu:com.leosradioexplorer/podcast_episode_started/jsonschema/1-0-0',
        data: podcastEpisodeStarted
    }
}
/**
 * Track a Snowplow event for PodcastUnsubscribed.
 * Fired when a user unsubscribes from a podcast
 */
export function trackPodcastUnsubscribed<T extends {} = any>(podcastUnsubscribed: PodcastUnsubscribed & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = podcastUnsubscribed;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosradioexplorer/podcast_unsubscribed/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow PodcastUnsubscribed entity.
 */
export function createPodcastUnsubscribed(podcastUnsubscribed: PodcastUnsubscribed){
    return {
        schema: 'iglu:com.leosradioexplorer/podcast_unsubscribed/jsonschema/1-0-0',
        data: podcastUnsubscribed
    }
}
/**
 * Track a Snowplow event for PlaylistStarted.
 * Fired when a user starts playing a playlist
 */
export function trackPlaylistStarted<T extends {} = any>(playlistStarted: PlaylistStarted & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = playlistStarted;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosradioexplorer/playlist_started/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow PlaylistStarted entity.
 */
export function createPlaylistStarted(playlistStarted: PlaylistStarted){
    return {
        schema: 'iglu:com.leosradioexplorer/playlist_started/jsonschema/1-0-0',
        data: playlistStarted
    }
}
/**
 * Track a Snowplow event for PodcastVisited.
 * Fired when a user visits a podcast detail page
 */
export function trackPodcastVisited<T extends {} = any>(podcastVisited: PodcastVisited & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = podcastVisited;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosradioexplorer/podcast_visited/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow PodcastVisited entity.
 */
export function createPodcastVisited(podcastVisited: PodcastVisited){
    return {
        schema: 'iglu:com.leosradioexplorer/podcast_visited/jsonschema/1-0-0',
        data: podcastVisited
    }
}
/**
 * Track a Snowplow event for RadioVisited.
 * Fired when a user visits a radio station detail page
 */
export function trackRadioVisited<T extends {} = any>(radioVisited: RadioVisited & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = radioVisited;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosradioexplorer/radio_visited/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow RadioVisited entity.
 */
export function createRadioVisited(radioVisited: RadioVisited){
    return {
        schema: 'iglu:com.leosradioexplorer/radio_visited/jsonschema/1-0-0',
        data: radioVisited
    }
}
/**
 * Track a Snowplow event for GenreVisited.
 * Fired when a user visits a genre page
 */
export function trackGenreVisited<T extends {} = any>(genreVisited: GenreVisited & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = genreVisited;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosradioexplorer/genre_visited/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow GenreVisited entity.
 */
export function createGenreVisited(genreVisited: GenreVisited){
    return {
        schema: 'iglu:com.leosradioexplorer/genre_visited/jsonschema/1-0-0',
        data: genreVisited
    }
}
/**
 * Track a Snowplow event for PodcastSubscribed.
 * Fired when a user subscribes to a podcast
 */
export function trackPodcastSubscribed<T extends {} = any>(podcastSubscribed: PodcastSubscribed & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = podcastSubscribed;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosradioexplorer/podcast_subscribed/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow PodcastSubscribed entity.
 */
export function createPodcastSubscribed(podcastSubscribed: PodcastSubscribed){
    return {
        schema: 'iglu:com.leosradioexplorer/podcast_subscribed/jsonschema/1-0-0',
        data: podcastSubscribed
    }
}

/**
 * Tracks a PodcastEpisodeStarted event specification.
 * ID: 1e201ab2-1fa8-46a5-bdb7-37a1653e7c95
 */
export function trackPodcastEpisodeStartedSpec(podcastEpisodeStarted: PodcastEpisodeStarted & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '1e201ab2-1fa8-46a5-bdb7-37a1653e7c95',
        version: 1,
        name: 'podcast_episode_started',
        data_product_id: '52f425f5-1bce-4349-929e-5c53dede1f07',
        data_product_name: 'Leo&#x27;s Radio Explorer Tracking Plan'
    });

    const context = Array.isArray(podcastEpisodeStarted.context)
        ? [...podcastEpisodeStarted.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedPodcastEpisodeStarted = {
        ...podcastEpisodeStarted,
        context,
    };

    trackPodcastEpisodeStarted<Record<string, unknown> | EventSpecification>(modifiedPodcastEpisodeStarted, trackers);
}
/**
 * Tracks a PodcastUnsubscribed event specification.
 * ID: 3e701b88-05a8-4fa4-bef7-9ca528a4564f
 */
export function trackPodcastUnsubscribedSpec(podcastUnsubscribed: PodcastUnsubscribed & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '3e701b88-05a8-4fa4-bef7-9ca528a4564f',
        version: 1,
        name: 'podcast_unsubscribed',
        data_product_id: '52f425f5-1bce-4349-929e-5c53dede1f07',
        data_product_name: 'Leo&#x27;s Radio Explorer Tracking Plan'
    });

    const context = Array.isArray(podcastUnsubscribed.context)
        ? [...podcastUnsubscribed.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedPodcastUnsubscribed = {
        ...podcastUnsubscribed,
        context,
    };

    trackPodcastUnsubscribed<Record<string, unknown> | EventSpecification>(modifiedPodcastUnsubscribed, trackers);
}
/**
 * Tracks a PlaylistStarted event specification.
 * ID: 500f9c2a-d5de-469c-af6f-626b8c9af62d
 */
export function trackPlaylistStartedSpec(playlistStarted: PlaylistStarted & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '500f9c2a-d5de-469c-af6f-626b8c9af62d',
        version: 1,
        name: 'playlist_started',
        data_product_id: '52f425f5-1bce-4349-929e-5c53dede1f07',
        data_product_name: 'Leo&#x27;s Radio Explorer Tracking Plan'
    });

    const context = Array.isArray(playlistStarted.context)
        ? [...playlistStarted.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedPlaylistStarted = {
        ...playlistStarted,
        context,
    };

    trackPlaylistStarted<Record<string, unknown> | EventSpecification>(modifiedPlaylistStarted, trackers);
}
/**
 * Tracks a PodcastVisited event specification.
 * ID: 57623aa9-2bf4-4f04-ab42-d8f25490bae0
 */
export function trackPodcastVisitedSpec(podcastVisited: PodcastVisited & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '57623aa9-2bf4-4f04-ab42-d8f25490bae0',
        version: 1,
        name: 'podcast_visited',
        data_product_id: '52f425f5-1bce-4349-929e-5c53dede1f07',
        data_product_name: 'Leo&#x27;s Radio Explorer Tracking Plan'
    });

    const context = Array.isArray(podcastVisited.context)
        ? [...podcastVisited.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedPodcastVisited = {
        ...podcastVisited,
        context,
    };

    trackPodcastVisited<Record<string, unknown> | EventSpecification>(modifiedPodcastVisited, trackers);
}
/**
 * Tracks a RadioVisited event specification.
 * ID: 8e6445c2-b352-4d97-bc8c-a96aca2eee28
 */
export function trackRadioVisitedSpec(radioVisited: RadioVisited & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '8e6445c2-b352-4d97-bc8c-a96aca2eee28',
        version: 1,
        name: 'radio_visited',
        data_product_id: '52f425f5-1bce-4349-929e-5c53dede1f07',
        data_product_name: 'Leo&#x27;s Radio Explorer Tracking Plan'
    });

    const context = Array.isArray(radioVisited.context)
        ? [...radioVisited.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedRadioVisited = {
        ...radioVisited,
        context,
    };

    trackRadioVisited<Record<string, unknown> | EventSpecification>(modifiedRadioVisited, trackers);
}
/**
 * Tracks a GenreVisited event specification.
 * ID: ef7a289d-d3bf-49cf-b89b-19e37327850d
 */
export function trackGenreVisitedSpec(genreVisited: GenreVisited & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: 'ef7a289d-d3bf-49cf-b89b-19e37327850d',
        version: 1,
        name: 'genre_visited',
        data_product_id: '52f425f5-1bce-4349-929e-5c53dede1f07',
        data_product_name: 'Leo&#x27;s Radio Explorer Tracking Plan'
    });

    const context = Array.isArray(genreVisited.context)
        ? [...genreVisited.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedGenreVisited = {
        ...genreVisited,
        context,
    };

    trackGenreVisited<Record<string, unknown> | EventSpecification>(modifiedGenreVisited, trackers);
}
/**
 * Track a Snowplow event for CountryVisited.
 * Fired when a user visits a country page
 */
export function trackCountryVisited<T extends {} = any>(countryVisited: CountryVisited & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = countryVisited;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosradioexplorer/country_visited/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow CountryVisited entity.
 */
export function createCountryVisited(countryVisited: CountryVisited){
    return {
        schema: 'iglu:com.leosradioexplorer/country_visited/jsonschema/1-0-0',
        data: countryVisited
    }
}
/**
 * Tracks a CountryVisited event specification.
 * ID: c7a92e1f-3b4d-4e8a-b6f0-d9e2c5a17083
 */
export function trackCountryVisitedSpec(countryVisited: CountryVisited & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: 'c7a92e1f-3b4d-4e8a-b6f0-d9e2c5a17083',
        version: 1,
        name: 'country_visited',
        data_product_id: '52f425f5-1bce-4349-929e-5c53dede1f07',
        data_product_name: 'Leo&#x27;s Radio Explorer Tracking Plan'
    });

    const context = Array.isArray(countryVisited.context)
        ? [...countryVisited.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedCountryVisited = {
        ...countryVisited,
        context,
    };

    trackCountryVisited<Record<string, unknown> | EventSpecification>(modifiedCountryVisited, trackers);
}
/**
 * Tracks a PodcastSubscribed event specification.
 * ID: f7ee111c-7f78-4727-b6a3-272ee3a28426
 */
export function trackPodcastSubscribedSpec(podcastSubscribed: PodcastSubscribed & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: 'f7ee111c-7f78-4727-b6a3-272ee3a28426',
        version: 1,
        name: 'podcast_subscribed',
        data_product_id: '52f425f5-1bce-4349-929e-5c53dede1f07',
        data_product_name: 'Leo&#x27;s Radio Explorer Tracking Plan'
    });

    const context = Array.isArray(podcastSubscribed.context)
        ? [...podcastSubscribed.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedPodcastSubscribed = {
        ...podcastSubscribed,
        context,
    };

    trackPodcastSubscribed<Record<string, unknown> | EventSpecification>(modifiedPodcastSubscribed, trackers);
}


