/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodcastsIndexRouteImport } from './routes/podcasts/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as GenresIndexRouteImport } from './routes/genres/index'
import { Route as CountriesIndexRouteImport } from './routes/countries/index'
import { Route as StationsStationIdRouteImport } from './routes/stations/$stationId'
import { Route as PodcastsPodcastIdRouteImport } from './routes/podcasts/$podcastId'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists/$playlistId'
import { Route as GenresGenreRouteImport } from './routes/genres/$genre'
import { Route as CountriesCountryRouteImport } from './routes/countries/$country'
import { Route as ApiServiceAttributesRouteImport } from './routes/api/service-attributes'
import { Route as PodcastsPodcastIdEpisodesEpisodeIdRouteImport } from './routes/podcasts/$podcastId.episodes.$episodeId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsIndexRoute = PodcastsIndexRouteImport.update({
  id: '/podcasts/',
  path: '/podcasts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresIndexRoute = GenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsStationIdRoute = StationsStationIdRouteImport.update({
  id: '/stations/$stationId',
  path: '/stations/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsPodcastIdRoute = PodcastsPodcastIdRouteImport.update({
  id: '/podcasts/$podcastId',
  path: '/podcasts/$podcastId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresGenreRoute = GenresGenreRouteImport.update({
  id: '/genres/$genre',
  path: '/genres/$genre',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCountryRoute = CountriesCountryRouteImport.update({
  id: '/countries/$country',
  path: '/countries/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServiceAttributesRoute = ApiServiceAttributesRouteImport.update({
  id: '/api/service-attributes',
  path: '/api/service-attributes',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsPodcastIdEpisodesEpisodeIdRoute =
  PodcastsPodcastIdEpisodesEpisodeIdRouteImport.update({
    id: '/episodes/$episodeId',
    path: '/episodes/$episodeId',
    getParentRoute: () => PodcastsPodcastIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/api/service-attributes': typeof ApiServiceAttributesRoute
  '/countries/$country': typeof CountriesCountryRoute
  '/genres/$genre': typeof GenresGenreRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/podcasts/$podcastId': typeof PodcastsPodcastIdRouteWithChildren
  '/stations/$stationId': typeof StationsStationIdRoute
  '/countries/': typeof CountriesIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/podcasts/': typeof PodcastsIndexRoute
  '/podcasts/$podcastId/episodes/$episodeId': typeof PodcastsPodcastIdEpisodesEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/api/service-attributes': typeof ApiServiceAttributesRoute
  '/countries/$country': typeof CountriesCountryRoute
  '/genres/$genre': typeof GenresGenreRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/podcasts/$podcastId': typeof PodcastsPodcastIdRouteWithChildren
  '/stations/$stationId': typeof StationsStationIdRoute
  '/countries': typeof CountriesIndexRoute
  '/genres': typeof GenresIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/podcasts': typeof PodcastsIndexRoute
  '/podcasts/$podcastId/episodes/$episodeId': typeof PodcastsPodcastIdEpisodesEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/api/service-attributes': typeof ApiServiceAttributesRoute
  '/countries/$country': typeof CountriesCountryRoute
  '/genres/$genre': typeof GenresGenreRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/podcasts/$podcastId': typeof PodcastsPodcastIdRouteWithChildren
  '/stations/$stationId': typeof StationsStationIdRoute
  '/countries/': typeof CountriesIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/podcasts/': typeof PodcastsIndexRoute
  '/podcasts/$podcastId/episodes/$episodeId': typeof PodcastsPodcastIdEpisodesEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/api/service-attributes'
    | '/countries/$country'
    | '/genres/$genre'
    | '/playlists/$playlistId'
    | '/podcasts/$podcastId'
    | '/stations/$stationId'
    | '/countries/'
    | '/genres/'
    | '/playlists/'
    | '/podcasts/'
    | '/podcasts/$podcastId/episodes/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/api/service-attributes'
    | '/countries/$country'
    | '/genres/$genre'
    | '/playlists/$playlistId'
    | '/podcasts/$podcastId'
    | '/stations/$stationId'
    | '/countries'
    | '/genres'
    | '/playlists'
    | '/podcasts'
    | '/podcasts/$podcastId/episodes/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/api/service-attributes'
    | '/countries/$country'
    | '/genres/$genre'
    | '/playlists/$playlistId'
    | '/podcasts/$podcastId'
    | '/stations/$stationId'
    | '/countries/'
    | '/genres/'
    | '/playlists/'
    | '/podcasts/'
    | '/podcasts/$podcastId/episodes/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LibraryRoute: typeof LibraryRoute
  SearchRoute: typeof SearchRoute
  ApiServiceAttributesRoute: typeof ApiServiceAttributesRoute
  CountriesCountryRoute: typeof CountriesCountryRoute
  GenresGenreRoute: typeof GenresGenreRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  PodcastsPodcastIdRoute: typeof PodcastsPodcastIdRouteWithChildren
  StationsStationIdRoute: typeof StationsStationIdRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  GenresIndexRoute: typeof GenresIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  PodcastsIndexRoute: typeof PodcastsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/': {
      id: '/podcasts/'
      path: '/podcasts'
      fullPath: '/podcasts/'
      preLoaderRoute: typeof PodcastsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/': {
      id: '/genres/'
      path: '/genres'
      fullPath: '/genres/'
      preLoaderRoute: typeof GenresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$stationId': {
      id: '/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof StationsStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$podcastId': {
      id: '/podcasts/$podcastId'
      path: '/podcasts/$podcastId'
      fullPath: '/podcasts/$podcastId'
      preLoaderRoute: typeof PodcastsPodcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/$genre': {
      id: '/genres/$genre'
      path: '/genres/$genre'
      fullPath: '/genres/$genre'
      preLoaderRoute: typeof GenresGenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$country': {
      id: '/countries/$country'
      path: '/countries/$country'
      fullPath: '/countries/$country'
      preLoaderRoute: typeof CountriesCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/service-attributes': {
      id: '/api/service-attributes'
      path: '/api/service-attributes'
      fullPath: '/api/service-attributes'
      preLoaderRoute: typeof ApiServiceAttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$podcastId/episodes/$episodeId': {
      id: '/podcasts/$podcastId/episodes/$episodeId'
      path: '/episodes/$episodeId'
      fullPath: '/podcasts/$podcastId/episodes/$episodeId'
      preLoaderRoute: typeof PodcastsPodcastIdEpisodesEpisodeIdRouteImport
      parentRoute: typeof PodcastsPodcastIdRoute
    }
  }
}

interface PodcastsPodcastIdRouteChildren {
  PodcastsPodcastIdEpisodesEpisodeIdRoute: typeof PodcastsPodcastIdEpisodesEpisodeIdRoute
}

const PodcastsPodcastIdRouteChildren: PodcastsPodcastIdRouteChildren = {
  PodcastsPodcastIdEpisodesEpisodeIdRoute:
    PodcastsPodcastIdEpisodesEpisodeIdRoute,
}

const PodcastsPodcastIdRouteWithChildren =
  PodcastsPodcastIdRoute._addFileChildren(PodcastsPodcastIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibraryRoute: LibraryRoute,
  SearchRoute: SearchRoute,
  ApiServiceAttributesRoute: ApiServiceAttributesRoute,
  CountriesCountryRoute: CountriesCountryRoute,
  GenresGenreRoute: GenresGenreRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  PodcastsPodcastIdRoute: PodcastsPodcastIdRouteWithChildren,
  StationsStationIdRoute: StationsStationIdRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  GenresIndexRoute: GenresIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  PodcastsIndexRoute: PodcastsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
